[package]
name    = "ecdsa"
version = "0.10.2" # Also update html_root_url in lib.rs when bumping this
description   = """
Signature and elliptic curve types providing interoperable support for the
Elliptic Curve Digital Signature Algorithm (ECDSA)
"""
authors    = ["RustCrypto Developers"]
license    = "Apache-2.0 OR MIT"
repository = "https://github.com/RustCrypto/signatures"
edition    = "2018"
readme     = "README.md"
categories = ["cryptography", "no-std"]
keywords   = ["crypto", "ecc", "nist", "secp256k1", "signature"]

[dependencies]
elliptic-curve = { git = "https://github.com/oxidecomputer/RustCrypto_traits.git", branch = "oxide_branch", default-features = false }
hmac = { version = "0.10", optional = true, default-features = false }
signature = { version = ">= 1.2.2, < 1.3.0", default-features = false, features = ["rand-preview"] }

[dev-dependencies]
#elliptic-curve = { version = "0.8.3", default-features = false, features = ["dev"] }
elliptic-curve = { git = "https://github.com/oxidecomputer/RustCrypto_traits.git", branch = "oxide_branch", default-features = false, features = ["dev"] }
hex-literal = "0.2"
sha2 = { version = "0.9", default-features = false }

[features]
default = ["digest"]
alloc = []
arithmetic = ["elliptic-curve/arithmetic"]
dev = ["arithmetic", "digest", "zeroize"]
digest = ["elliptic-curve/digest", "signature/digest-preview"]
hazmat = []
pkcs8 = ["elliptic-curve/pkcs8"]
pem = ["elliptic-curve/pem", "pkcs8"]
sign = ["arithmetic", "digest", "hazmat", "hmac", "zeroize"]
std = ["alloc", "elliptic-curve/std", "signature/std"]
verify = ["arithmetic", "digest", "hazmat"]
zeroize = ["elliptic-curve/zeroize"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
